### ISSUE TITLE
reset the input borders after clicking reset

### ISSUE THREAD

**Issue by Amenawon** [zachbharris/wpm#4]
On resetting the game, the red borders are still apparent when it should be reset
<img width="805" alt="Screenshot 2024-01-08 at 00 08 59" src="https://github.com/zachbharris/wpm/assets/38262375/1e881e08-40c2-476e-9842-43a1efa9313c">

**Comment by zachbharris** [comment]
Interesting! I'll take a look and see what I can find. 😄

**Comment by zachbharris** [comment]
I'll have a fix in the next release later tonight. Thanks for bringing this to my attention!
